---
- hosts: ubuntu
  become: true
 
  tasks:

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'git', 'apt-transport-https', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
     
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: 
      update_cache: yes 
      name: docker-ce 
      state: latest

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Clone a github repository
    ansible.builtin.git:
        repo: https://github.com/warcan-max/react-redux-realworld-example-app.git
        dest: /app
        clone: yes

  - name: Build Docker image
    docker_image:
      name: appimage
      build:
        path: /app
      source: build

  - name: Start docker contsiner 
    docker_container:
      name: docker_app
      image: appimage
      ports:
        - "80:80"
      state: started

- hosts: localhost
  vars:
      url: http://172.16.90.130    
  tasks:  
    
  - name: Get Status code 
    ansible.builtin.shell: curl -LI {{ url }} -o /dev/null -w '%{http_code}\n' -s
    register: codestatus 
  - debug: 
      msg: "The URL {{ url }} returned {{ codestatus.stdout }}"
    